### ISSUE TITLE
Cluster initial master node must be commented on Elastic 8.3

### ISSUE THREAD

**Issue by Sh4dow-BR** [PacktPublishing/Threat-Hunting-with-Elastic-Stack#2]
Hello there!

While having resolved the previous issue, I still had problems starting the elastic instance.

When I checked the logs, I noticed that there was an automatic cluster starting.
Perhaps as a new default configuration, the initial cluster isn't commented by default.

When I commented, "cluster.initial_master_nodes", I was able to finally start my instance without an issue.

Since in the lab and book, we are creating a single node, it was causing conflicts with the option turned on.

```
# --------------------------------------------------------------------------------

# Enable security features
xpack.security.enabled: true

xpack.security.enrollment.enabled: true

# Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/http.p12

# Enable encryption and mutual authentication between cluster nodes
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12
# Create a new cluster with the current node only
# Additional nodes can still join the cluster later
 cluster.initial_master_nodes: ["STATIC HOST NAME HERE IN THIS FIELD"]

# Allow HTTP API connections from anywhere
# Connections are encrypted and require user authentication
http.host: 0.0.0.0

# Allow other nodes to join the cluster from anywhere
# Connections are encrypted and mutually authenticated
#transport.host: 0.0.0.0

```

Doing the following, resolved the issue:
`# cluster.initial_master_nodes: ["STATIC HOST NAME HERE IN THIS FIELD"]`

Thanks once again!
