### ISSUE TITLE
After adding the system module to filebeat, it's necessary to enable the config reload on Elastic 8.3

### ISSUE THREAD

**Issue by Sh4dow-BR** [PacktPublishing/Threat-Hunting-with-Elastic-Stack#4]
Hello!

After adding the system module to filebeat, I had the following error: 
_Exiting: Failed to start crawler: creating module reloader failed: could not create module registry for filesets: module system is configured but has no enabled filesets_

After checking the filebeats.yml, I saw that there was an option to reload the configs.

```
# ============================== Filebeat modules ==============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

```

Changing reload.enabled from false to true solved the problem.
` reload.enabled: true`
